@tool
extends CSGPolygon3D

#changing position of csg mesh that is generated by the curve
#centers the 
@export var offset = 2.0:
	set(new_offset):
		offset = new_offset
		polygon = PackedVector2Array([
			Vector2(-offset/2, -offset/2),
			Vector2(-offset/2, offset/2),
			Vector2(offset/2, offset/2),
   			Vector2(offset/2, -offset/2),
			])
